paths:

  posts: "./data/posts.csv"
  comments: "./data/comments.csv"
  reddit_users: "./data/users.csv"
  user_follow: "./data/user_follow.csv"

log:
  log_file: "out.log"

constants:
  page_size: 5

time:
  start_time: "2024-02-15 00:00:00"
  end_time: "2024-03-15 23:59:59"



actions:
  # BrowsePost: action.BrowsePost
  BrowseHotsInitPage: action.BrowseHotsInitPage
  BrowseHotsSelectPage: action.BrowseHotsSelectPage
  PostAction: action.PostAction
  CommentAction: action.CommentAction
  SearchPostAction: action.SearchPostAction
  SearchUserAction: action.SearchUserAction
  CreateUserAction: action.CreateUserAction
  BrowseRecommendFeed: action.BrowseRecommendFeed
  FollowAction: action.FollowAction
  LikeAction: action.LikeAction
  DislikeAction: action.DislikeAction
  StopAction: action.StopAction